### ISSUE TITLE
indexing on Elasticsearch still not working

### ISSUE THREAD

**Issue by fccoelho** [NAMD/mediacloud_backend#75]
@flavioamieiro: the new import also failed.

**Comment by fccoelho** [comment]
the indexing of the captured articles if working nicely. we just have to figure out what is failing in the backlog indexing

**Comment by fccoelho** [comment]
perhaps we should try moving to bulk inserts: http://elasticsearch-py.readthedocs.org/en/latest/helpers.html#elasticsearch.helpers.bulk

**Comment by flavioamieiro** [comment]
This might be a good idea. I think we should also try to figure out why it says the documents are there, but with no content.

**Comment by fccoelho** [comment]
The index function returns some information, we should check it for errors
Em 05/02/2015 16:37, "Flávio Amieiro" <notifications@github.com> escreveu:
