### ISSUE TITLE
Error when saving the url on mongo

### ISSUE THREAD

**Issue by flavioamieiro** [NAMD/mediacloud_backend#97]
When checking the database for compatibility with mongo 2.6 (so we can then upgrade to 3.0) I stumbled on the following error:

    Document Error: key for index {  "v" : 1,  "name" : "url_1",  "key" : {  "url" : 1 },  "unique" : true,  "ns" : "MCDB.urls" } too long for document: {  "_id" : ObjectId("5494a711dcccdd10afbb7c11"),  "url" : "http://saojoaquimonline.com.br/saojoaquimdefato/Neva na Serra catarinense na noite desta terça-feira/serrasc.com.br/A unidade da Epagri em Caçador, está desenvolvendo quatro novas cultivares de macieiras. O comitê técnico da Associação Brasileira dos Produtores de MaçãABPM já fez testes sensoriais com os novos cruzamentos que estão sendo propostos pela pesquisa, tendo como referências as variedades Baronesa e Imperatriz./www.saojoaquimonline.com.br/www.festivalbrasil.jp/serrasc.com.br/A unidade da Epagri em Caçador, está desenvolvendo quatro novas cultivares de macieiras. O comitê técnico da Associação Brasileira dos Produtores de MaçãABPM já fez testes sensoriais com os novos cruzamentos que estão sendo propostos pela pesquisa, tendo como referências as variedades Baronesa e Imperatriz./serrasc.com.br/www.festivalbrasil.jp/A unidade da Epagri em Caçador, está desenvolvendo quatro novas cultivares de macieiras. O comitê técnico da Associação Brasileira dos Produtores de MaçãABPM já fez testes sensoriais com os novos cruzamentos que estão sendo propostos pela pesquisa, tendo como referências as variedades Baronesa e Imperatriz./?paged=104",  "fetched_on" : ISODate("2014-12-19T20:30:41.555Z"),  "tags" : [ "filmes+policia+ambiente+colunistas+alimento" ] }

We need to solve this before we can upgrade to 2.6. I think the problem is happening in (googlerss.py, when getting the url)[https://github.com/NAMD/mediacloud_backend/blob/master/capture/googlerss.py#L63]. After the split on '&' we get all the text if there is no '&' on the original.

What I don't understand is how the text is getting to the url we get from `url.geturl()`.

@fccoelho any idea on why this is happening?

**Comment by fccoelho** [comment]
@flavioamieiro , I remember adding this split to remove the things google appended to the url to track who clicks on each link. The only thing I can think is happening, is that google may have changed the way it builds the url. Try to run googlerss in a debugger to see what is going on.

**Comment by flavioamieiro** [comment]
@fccoelho the problem is definetly happening when the url is in an unexpected format. What I don't understand is how we are getting text (such as `Neva na Serra catarinense`) in the result of `url.geturl()`.

**Comment by rsouza** [comment]
There are some URLs that bring the headline of the news in it. See, for
example:
http://dc.clicrbs.com.br/sc/noticias/noticia/2015/11/transporte-coletivo-so-sera-normalizado-apos-pagamento-dos-funcionarios-afirma-sindicato-4898075.html
It may somehow turn into text like you observed.

2015-11-09 13:47 GMT-05:00 Flávio Amieiro <notifications@github.com>:

**Comment by fccoelho** [comment]
@flavioamieiro , can we close this now?

**Comment by flavioamieiro** [comment]
Yes, I've removed these urls and fixed other indexes that had problems.
